# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: product_development
  username: root
  password: mysql
  host: localhost
test:
  adapter: mysql2
  database: product_test
  username: root
  password: mysql
  host: localhost
production:
  adapter: mysql2
  database: product_production
  username: root
  password: mysql
  host: localhost